# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_his.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1080)
        MainWindow.setTabletTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1100, 70, 201, 41))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background:#6C6C6C;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 20px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 930, 161, 41))
        self.label_3.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(790, 140, 241, 40))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"        border:1px solid gray;\n"
"        width:300px;\n"
"        border-radius:12px;\n"
"        padding:2px 4px;\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(230, 580, 241, 41))
        self.textBrowser_6.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1100, 140, 201, 41))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background:#6C6C6C;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 20px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("source/cloud-computing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 580, 161, 41))
        self.label_10.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_10.setObjectName("label_10")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 510, 241, 41))
        self.textBrowser.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 140, 241, 40))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"        border:1px solid gray;\n"
"        width:300px;\n"
"        border-radius:12px;\n"
"        padding:2px 4px;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(230, 1000, 241, 41))
        self.textBrowser_4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(790, 334, 72, 21))
        self.label_5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(600, 140, 171, 40))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background:#6C6C6C;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 14px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(600, 70, 171, 40))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background:#6C6C6C;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 14px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 70, 171, 40))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_2.setToolTip("")
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background:#6C6C6C;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 14px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 510, 161, 41))
        self.label.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(1530, 334, 72, 21))
        self.label_8.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(230, 650, 241, 41))
        self.textBrowser_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(230, 720, 241, 41))
        self.textBrowser_5.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(501, 361, 640, 640))
        self.label_6.setStyleSheet("background-color :rgb(0, 0, 0); \n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 1000, 161, 41))
        self.label_4.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 300, 291, 61))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background:#6C6C6C;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 25px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("source/go.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 70, 241, 40))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"        border:1px solid gray;\n"
"        width:300px;\n"
"        border-radius:12px;\n"
"        padding:2px 4px;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1220, 360, 640, 640))
        self.label_7.setStyleSheet("background-color :rgb(0, 0, 0); \n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 140, 171, 40))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background:#6C6C6C;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 14px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(790, 70, 241, 40))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"        border:1px solid gray;\n"
"        width:300px;\n"
"        border-radius:12px;\n"
"        padding:2px 4px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(230, 930, 241, 41))
        self.textBrowser_3.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(70, 220, 151, 31))
        self.checkBox.setObjectName("checkBox")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(1450, 30, 431, 261))
        self.calendarWidget.setObjectName("calendarWidget")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(500, 360, 641, 641))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setText("")
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(340, 220, 761, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(1160, 230, 115, 19))
        self.radioButton.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(1160, 270, 115, 19))
        self.radioButton_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setEnabled(True)
        self.pushButton_9.setGeometry(QtCore.QRect(110, 400, 291, 61))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background:#6C6C6C;\n"
"color:white;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;border-radius: 25px;font-family: 微软雅黑;\n"
"}\n"
"QPushButton:hover{\n"
"background:#9D9D9D;\n"
"}\n"
"QPushButton:pressed{\n"
"border: 1px solid #3C3C3C!important;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("source/paint-roller.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setGeometry(QtCore.QRect(1340, 110, 71, 41))
        self.checkBox_2.setMouseTracking(True)
        self.checkBox_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 210, 111, 51))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"color:black;\n"
"box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:16px;\n"
"    font: 12pt \"微软雅黑\";\n"
"}\n"
"")
        self.pushButton_10.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("source/speed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon5)
        self.pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(40, 650, 181, 41))
        self.textBrowser_7.setAutoFillBackground(False)
        self.textBrowser_7.setStyleSheet("background-color :transparent;\n"
"font: 12pt \"微软雅黑\";\n"
"border:0px;")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(40, 720, 181, 41))
        self.textBrowser_8.setStyleSheet("background-color :transparent;\n"
"font: 12pt \"微软雅黑\";\n"
"border:0px;")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_zg = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_zg.setGeometry(QtCore.QRect(230, 790, 241, 41))
        self.textBrowser_zg.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.textBrowser_zg.setObjectName("textBrowser_zg")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 790, 161, 41))
        self.label_9.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_9.setObjectName("label_9")
        self.textBrowser_cyzg = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_cyzg.setGeometry(QtCore.QRect(230, 860, 241, 41))
        self.textBrowser_cyzg.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.textBrowser_cyzg.setObjectName("textBrowser_cyzg")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(50, 860, 161, 41))
        self.label_11.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "表型测量系统"))
        MainWindow.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "在Excel中进行数据分析"))
        self.pushButton_6.setText(_translate("MainWindow", "历史记录"))
        self.label_3.setText(_translate("MainWindow", "茎粗 MM"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>确保在选择要显示的点云种类后点击</p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "显示点云"))
        self.label_10.setText(_translate("MainWindow", "叶面积指数 %"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "俯视图"))
        self.pushButton_5.setText(_translate("MainWindow", "打开平视DEP"))
        self.pushButton_3.setText(_translate("MainWindow", "打开俯视DEP"))
        self.pushButton_2.setText(_translate("MainWindow", "打开俯视RGB"))
        self.label.setText(_translate("MainWindow", "叶片数量"))
        self.label_8.setText(_translate("MainWindow", "平视图"))
        self.label_4.setText(_translate("MainWindow", "叶片高 MM"))
        self.pushButton.setToolTip(_translate("MainWindow", "单击开始测量"))
        self.pushButton.setText(_translate("MainWindow", "开始测量"))
        self.pushButton_4.setText(_translate("MainWindow", "打开平视RGB"))
        self.checkBox.setToolTip(_translate("MainWindow", "调用GPU资源进行神经网络模型加速"))
        self.checkBox.setText(_translate("MainWindow", "使用GPU加速"))
        self.pushButton_8.setToolTip(_translate("MainWindow", "在测量后可点击此处选择叶片"))
        self.progressBar.setToolTip(_translate("MainWindow", "<html><head/><body><p>20%  测量线程初始化</p><p>30%  成功调用TensorFlow二进制文件</p><p>60%  叶片数，叶面积，叶面积指数测量完成</p><p>100% 测量完成</p></body></html>"))
        self.radioButton.setToolTip(_translate("MainWindow", "显示在俯视图中选择的叶片的点云"))
        self.radioButton.setText(_translate("MainWindow", "叶子点云"))
        self.radioButton_2.setToolTip(_translate("MainWindow", "显示俯视图点云（去除土壤）"))
        self.radioButton_2.setText(_translate("MainWindow", "群体点云"))
        self.pushButton_9.setToolTip(_translate("MainWindow", "使用生成对抗网络进行图像修复"))
        self.pushButton_9.setText(_translate("MainWindow", "图像修复"))
        self.checkBox_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>当RGB与深度图文件在同一文件夹时</p><p>可使用该选项</p></body></html>"))
        self.checkBox_2.setText(_translate("MainWindow", "自动"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt;\">平均叶面积 CM</span><span style=\" font-family:\'SimSun\'; font-size:14pt; vertical-align:super;\">2</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt;\">抽样叶面积 CM</span><span style=\" font-family:\'SimSun\'; font-size:14pt; vertical-align:super;\">2</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "冠层 MM"))
        self.label_11.setText(_translate("MainWindow", "抽样冠层 MM"))
