# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_child(object):
    def setupUi(self, child):
        child.setObjectName("child")
        child.resize(1800, 659)
        self.centralwidget = QtWidgets.QWidget(child)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_startcam = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_startcam.setGeometry(QtCore.QRect(50, 30, 181, 71))
        self.pushButton_startcam.setObjectName("pushButton_startcam")
        self.pushButton_frame = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_frame.setGeometry(QtCore.QRect(50, 120, 181, 71))
        self.pushButton_frame.setObjectName("pushButton_frame")
        self.labelrgb = QtWidgets.QLabel(self.centralwidget)
        self.labelrgb.setGeometry(QtCore.QRect(260, 30, 480, 270))
        self.labelrgb.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.labelrgb.setObjectName("labelrgb")
        self.labelrgb_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelrgb_2.setGeometry(QtCore.QRect(260, 340, 480, 270))
        self.labelrgb_2.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.labelrgb_2.setObjectName("labelrgb_2")
        self.labelrgb_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelrgb_3.setGeometry(QtCore.QRect(760, 30, 1031, 581))
        self.labelrgb_3.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.labelrgb_3.setObjectName("labelrgb_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1370, 600, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1400, 600, 72, 15))
        self.label_5.setObjectName("label_5")
        child.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(child)
        self.statusbar.setObjectName("statusbar")
        child.setStatusBar(self.statusbar)

        self.retranslateUi(child)
        QtCore.QMetaObject.connectSlotsByName(child)

    def retranslateUi(self, child):
        _translate = QtCore.QCoreApplication.translate
        child.setWindowTitle(_translate("child", "MainWindow"))
        self.pushButton_startcam.setText(_translate("child", "打开相机"))
        self.pushButton_frame.setText(_translate("child", "开始拍摄"))
        self.labelrgb.setText(_translate("child", "TextLabel"))
        self.labelrgb_2.setText(_translate("child", "TextLabel"))
        self.labelrgb_3.setText(_translate("child", "TextLabel"))
        self.label_4.setText(_translate("child", "RGB"))
        self.label_5.setText(_translate("child", "RGB"))
