# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhichi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1257, 714)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelrgb_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelrgb_2.setGeometry(QtCore.QRect(230, 340, 480, 270))
        self.labelrgb_2.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.labelrgb_2.setObjectName("labelrgb_2")
        self.pushButton_startcam = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_startcam.setGeometry(QtCore.QRect(20, 30, 181, 71))
        self.pushButton_startcam.setObjectName("pushButton_startcam")
        self.labelrgb_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelrgb_3.setGeometry(QtCore.QRect(730, 30, 1031, 581))
        self.labelrgb_3.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.labelrgb_3.setObjectName("labelrgb_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1370, 600, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1340, 600, 72, 15))
        self.label_4.setObjectName("label_4")
        self.pushButton_frame = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_frame.setGeometry(QtCore.QRect(20, 120, 181, 71))
        self.pushButton_frame.setObjectName("pushButton_frame")
        self.labelrgb = QtWidgets.QLabel(self.centralwidget)
        self.labelrgb.setGeometry(QtCore.QRect(230, 30, 480, 270))
        self.labelrgb.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.labelrgb.setObjectName("labelrgb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelrgb_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_startcam.setText(_translate("MainWindow", "打开相机"))
        self.labelrgb_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "RGB"))
        self.label_4.setText(_translate("MainWindow", "RGB"))
        self.pushButton_frame.setText(_translate("MainWindow", "开始拍摄"))
        self.labelrgb.setText(_translate("MainWindow", "TextLabel"))
